<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />

<meta name="author" content="Rob Knell" />


<meta name="progressive" content="false" />
<meta name="allow-skip" content="false" />

<title>Descriptive and Exploratory Statistics 2: Descriptive statistics</title>


<!-- highlightjs -->
<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>

<!-- taken from https://github.com/rstudio/rmarkdown/blob/67b7f5fc779e4cfdfd0f021d3d7745b6b6e17149/inst/rmd/h/default.html#L296-L362 -->
<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<script>
$(document).ready(function () {
  window.buildTabsets("section-TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>
<!-- end tabsets -->


<link rel="stylesheet" href="http://research.sbcs.qmul.ac.uk/r.knell/learnr_data/test2.css" type="text/css" />

</head>

<body>



<div class="pageContent band">
<div class="bandContent page">

<div class="topics">

<div id="section-what-is-the-purpose-of-descriptive-statistics" class="section level2">
<h2>What is the purpose of descriptive statistics?</h2>
<p>Figure 1 below is a frequency histogram showing measures of lysozyme activity for 194 men and women, from a study of the relationship between height and immunity in humans published in 2017<sup>1</sup>. Lysozyme is an enzyme that causes bacteria to lyse (hence the name) and its activity here was measured by incubating blood serum with a suspension of bacterial cells and comparing the optical absorption after 20 minutes with a control sample with no serum.</p>
<pre class="r"><code># Load data
height &lt;- read.csv(
  &quot;http://research.sbcs.qmul.ac.uk/r.knell/learnr_data/body_height_immunity.csv&quot;
  )

# Draw the histogram
hist(height$lysozyme,
     col = &quot;aquamarine4&quot;,
     main = &quot;&quot;,
     xlab = &quot;Lysozyme activity&quot;
)</code></pre>
<div class="figure">
<img src="Descriptive-statistics_files/figure-html/unnamed-chunk-1-1.png" alt="**Figure 1** Frequency histogram of lysozyme activity for 194 people" width="384" />
<p class="caption">
<strong>Figure 1</strong> Frequency histogram of lysozyme activity for 194 people
</p>
</div>
<p>When we visualise these data using a frequency histogram we can see that these values are centred around a value of roughly 0.35-0.4, with the majority of people in the sample having activity between 0.3 and 0.5 and almost all of them having values between 0.2 and 0.55. We can also see that the distribution of data is roughly symmetrical and approximately normally distributed, although there does seem to be some indication of slight negative skew — the lower tail of the distribution looks rather fatter than the upper tail, and the lowest value is further from the centre of the distribution than the highest value is.</p>
<p>We can see these things from just looking at the histogram, but if we want to go further we need to quantify these observations. If we want to know whether for example,some treatment we might use causes a change in lysozyme activity we need to calculate where the centre of the distribution is, and if we suspect that our treatment causes a change in the amount of variability in the data then we need to quantify the amount of spread, or <em>dispersion</em> there is in these data. Knowing this can also let us assess how likely or unlikely particular values might be: for example, if we had a person with an activity measured at 0.9 we might want to ask whether that high value was something that might be expected given the distribution of data, or whether that value might indicate an anomaly where perhaps there was something different about that person that might cause higher lysozyme activity, such as a genetic difference, a recent infection or something similar. We’ll start with the ways that we can describe the centre of the distribution of data.</p>
<br><br>
<hr>
<p><sup>1</sup> Pawłowski, B., Nowak, J., Borkowska, B., Augustyniak, D. &amp; Drulis-Kawa, Z. (2017) Body height and immune efficacy: testing body stature as a signal of biological quality. Proceedings. Biological sciences / The Royal Society, 284: 0171372</p>
</div>
<div id="section-the-three-ms-mean-median-and-mode-as-measures-of-central-tendency" class="section level2">
<h2>The three <strong>M</strong>s: Mean, Median and Mode as Measures of Central Tendency</h2>
<p>Before starting on this section, you might like to watch this short video explaining means and medians:</p>
<p><img src="https://youtu.be/alqrNPS7MYw" /></p>
<div id="section-mean" class="section level3">
<h3>Mean</h3>
<p>The most common statistic used to describe where the middle of a dataset is is the <em>arithmetic mean</em>, usually just called the <em>mean</em>. This is also the figure that most people are thinking of when they say the <em>average</em>. It’s dead simple to calculate: you add all of the numbers up, and then you divide that figure by the number of datapoints. To put this more formally,</p>
<p><span class="math display">\[ \large{\bar{x} = \frac{\Sigma x}{n}}\]</span></p>
<p>Here, <span class="math inline">\(\bar{x}\)</span> represents the sample mean, the <span class="math inline">\(\Sigma\)</span> in the equation is a capital sigma and is used to mean “the sum of”, <span class="math inline">\(x\)</span> refers to our data and <span class="math inline">\(n\)</span> is the sample size. So this is just saying “to get the mean, add all the data together and divide my the sample size” but in statisticalese. If we had only sampled lysozyme activity from 7 people then our data might look like this: <br> <span class="math display">\[0.37, 0.22, 0.50, 0.53, 0.38, 0.35, 0.23\]</span> <br> and we could calculate the mean of these data as follows:</p>
<p><br></p>
<p><span class="math display">\[ \bar{x} = \frac{0.37 + 0.22 + 0.50+ 0.53+ 0.38+ 0.35+ 0.23}{7} = \frac{2.58}{7} = 0.37 \]</span> <br> We end up with a value for <span class="math inline">\(\bar{x}\)</span> of just under 0.4, which concides nicely with the peak of the distribution. Since our <span class="math inline">\(n\)</span> is actually 194 it would be a little cumbersome to write out the calculation for the mean of all the data, but fortunately R has a built in function to calculate the mean called, surprisingly, <code>mean()</code>.</p>
<pre class="r"><code>mean(height$lysozyme)</code></pre>
<pre><code>## [1] 0.3768497</code></pre>
<p>Giving us a value for <span class="math inline">\(\bar{x}\)</span> which is surprisingly close to the one we got from just seven values. This is more by accident than design.</p>
</div>
<div id="section-median" class="section level3">
<h3>Median</h3>
<p>The next most common statistic that you’ll see used to describe the centre of a distribution is the <em>median</em>. This is, quite simply, the number in the middle of the distribution. You <em>rank</em> all your data from low to high (or <em>vice-versa</em>), and the number in the middle is the median. So, returning to our seven number subset from before:</p>
<p><span class="math display">\[0.37, 0.22, 0.50, 0.53, 0.38, 0.35, 0.23\]</span> we can rank these, starting with the lowest:</p>
<p><span class="math display">\[0.22, 0.23, 0.35, \underline{0.37}, 0.38, 0.50, 0.53.\]</span> The underlined value, 0.37, is the one in the middle and so is the median. This turns out to be exactly the same as the mean, and again this is more by accident than anything else. You can see that the median divides the data set into two equal halves, so half of the data have values greater than the median and half have values less than the median.</p>
<p>If you have an even number of data, of course there isn’t a value in the middle when you rank your data. What you do in this case to calculate the median is to take the two numbers that are in the middle and calculate the mean of those two to get your median.</p>
<p>For the median of our overall lysozyme variable, again R can very simply calculate this for you using the <code>median()</code> function.</p>
<pre class="r"><code>median(height$lysozyme)</code></pre>
<pre><code>## [1] 0.38</code></pre>
<p>This returns 0.38 so fractionally higher than the 0.37 for the mean.</p>
</div>
<div id="section-mode" class="section level3">
<h3>Mode</h3>
<p>The mode is the most common value in a dataset. It’s not used as much as the mean or the median, mainly because when you have continuous data which can take any value the mode doesn’t really have much meaning. Our lysozyme variable, for example, has 133 unique values out of 194 so asking which value is the most common isn’t really going to tell us a lot.</p>
<p>Modes can be valuable when you’re looking at categorical data, where each value can only take one of a limited number of values such as juvenile/adult or green/blue/red/yellow or healthy/unwell/incapacitated/dead but in these cases you can usually just look at a frequency histogram. R doesn’t even have a function to calculate the mode… somewhat perversely it does have a function called <code>mode()</code> but that tells you what the “storage mode” of a variable is:</p>
<pre class="r"><code>mode(height$lysozyme)</code></pre>
<pre><code>## [1] &quot;numeric&quot;</code></pre>
<p>So now you know not to get confused there…</p>
</div>
<div id="section-central-tendency-exercises" class="section level3">
<h3>Central tendency exercises</h3>
<div id="section-means-versus-medians" class="section level4">
<h4>Means versus medians</h4>
<p>Here are some more numbers from our lysozyme data:</p>
<p>0.22 0.39 0.36 0.45 0.41</p>
<p>Use the <code>c()</code> function to set up a vector of these data called <code>X1</code>, and calculate the mean and the median. Remember that because <code>X1</code> is saved straight into the workspace and isn’t part of a data frame you don’t need to use $ or anything like that to refer to it: just use the name.</p>
<div class="tutorial-exercise" data-label="mean1" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<script type="application/json" data-opts-chunk="1">{"fig.width":6.5,"fig.height":4,"fig.retina":2,"fig.align":"default","fig.keep":"high","fig.show":"asis","out.width":624,"warning":true,"error":false,"message":true,"exercise.df_print":"paged","exercise.checker":"NULL"}</script>
</div>
<div class="tutorial-exercise-support" data-label="mean1-hint-1" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code>#Don&#39;t forget to put commas between each 
#number for the vector, and make sure 
#you have the brackets done correctly 
#for all the functions you use.
#
#Don&#39;t forget that R is case sensitive so
#if you called your vector X1 then trying to
#calculate the mean of x1 won&#39;t work
#</code></pre>
</div>
<div class="tutorial-exercise-support" data-label="mean1-hint-2" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code>#For the vector you need to type this:

X1 &lt;- c(0.22, 0.39, 0.36, 0.45, 0.41)</code></pre>
</div>
<div class="tutorial-exercise-support" data-label="mean1-hint-3" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code>#This is the solution:

X1 &lt;- c(0.22, 0.39, 0.36, 0.45, 0.41)
mean(X1)
median(X1)</code></pre>
</div>
<p>This should give you a value of 0.366 for the mean and 0.39 for the median.</p>
<p>Now let’s look at what happens when we add another datapoint with a very high value. Somehow you’ve managed to measure someone’s lysozyme activity as 20. Generate a vector called X2 with the previous numbers you used and also a sixth value set at 20, and calculate the mean and the median again.</p>
<div class="tutorial-exercise" data-label="mean2" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<script type="application/json" data-opts-chunk="1">{"fig.width":6.5,"fig.height":4,"fig.retina":2,"fig.align":"default","fig.keep":"high","fig.show":"asis","out.width":624,"warning":true,"error":false,"message":true,"exercise.df_print":"paged","exercise.checker":"NULL"}</script>
</div>
<div class="tutorial-exercise-support" data-label="mean2-hint-1" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code>#For the vector you need to type this:

X1 &lt;- c(0.22, 0.39, 0.36, 0.45, 0.41, 20)</code></pre>
</div>
<div class="tutorial-exercise-support" data-label="mean2-hint-2" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code>#This is the solution:

X2 &lt;- c(0.22, 0.39, 0.36, 0.45, 0.41, 20)
mean(X2)
median(X2)</code></pre>
</div>
<p>Compare the values for the mean and the median for both X1 and X2. What do you notice about how they respond to the addition of an extreme value to the data?</p>
<p>Hopefully what you can see is that while the mean increased by about a factor of 10, from 0.37 to 3.64, the median hardly changed, going from 0.39 to 0.4. This illustrates a very important point about these two measures: the mean is <em>sensitive to outliers</em> which means that it responds strongly to very high or very low values, whereas the median does not and we would say that it is <em>robust to outliers</em>. In this case when we add the extra value to our data the mean changes to a number which is not really representative of the data at all: we have 5 values which are all well below 1, and 1 value of twenty, and somewhere in between them is the mean. The median on the other hand is still giving you some useful information about your vector of numbers.</p>
</div>
<div id="section-summarising-a-new-variable" class="section level4">
<h4>Summarising a new variable</h4>
<p>In the <code>height</code> data frame there is another variable called “phagocytic” which is a measure of the phagocytic response by the leucocytes for each person in the study. Calculate the mean and the median for this variable.</p>
<p><em>TIP</em> the <code>phagocytic</code> variable contains some missing data (<code>NA</code>). The default option for both the <code>mean()</code> and <code>median()</code> functions when presented with missing data is just to return <code>NA</code> and not calculate anything. If you want to get the mean or median calculated from the data that are present, you have to add this argument: <code>na.rm = TRUE</code> to your function call, so you’d have something like <code>median(my_variable_name, na.rm=TRUE)</code>.</p>
<div class="tutorial-exercise-support" data-label="prepare-height" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code>height &lt;- read.csv(
  &quot;http://research.sbcs.qmul.ac.uk/r.knell/learnr_data/body_height_immunity.csv&quot;
  )</code></pre>
</div>
<div class="tutorial-exercise" data-label="mean3" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<script type="application/json" data-opts-chunk="1">{"fig.width":6.5,"fig.height":4,"fig.retina":2,"fig.align":"default","fig.keep":"high","fig.show":"asis","out.width":624,"warning":true,"error":false,"message":true,"exercise.df_print":"paged","exercise.setup":"prepare-height","exercise.checker":"NULL"}</script>
</div>
<div class="tutorial-exercise-support" data-label="mean3-hint-1" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code>#As for the lysozyme data, we have to
#tell R to look in the height data frame 
#for the lysozyme vector. You do this by
#typing the name of the data frame, a dollar
#symbol and then the name of the variable.</code></pre>
</div>
<div class="tutorial-exercise-support" data-label="mean3-hint-2" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code>#Don&#39;t forget to put a comma between the 
#variable name and the na.rm = TRUE argument
#for both function calls.
#
#Don&#39;t forget that R is case sensitive and
#capital and lower case letters have to match
#
#Make sure that all your opening brackets 
#have closing brackets</code></pre>
</div>
<div class="tutorial-exercise-support" data-label="mean3-hint-3" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code>#This is the solution:

mean(height$phagocytic, na.rm = TRUE)
median(height$phagocytic, na.rm = TRUE)</code></pre>
</div>
<p>Compare the values for the mean and the median. Are they roughly the same? If not what might this tell you about this variable?</p>
<p>Let’s have a look at the shape of the <code>phagocytic</code> variable. Use the <code>hist()</code> function to plot a frequency histogram for this variable <code>phagocytic</code>. Let’s make it a nice plot so choose a suitable main title and set it using <code>main = "my_title"</code>, label the x axis “Phagocytic activity” using <code>xlab = ""</code> and use <code>col = ""</code> to set a colour for the bars. I’ll suggest “steelblue” or “sienna3” as giving nice results, or alternatively <a href="http://www.stat.columbia.edu/~tzheng/files/Rcolor.pdf">pick your own colour name from here</a>.</p>
<p>Have a look at the histograms tutorial if you’re really stuck and can’t remember anything about how <code>hist()</code> works.</p>
<div class="tutorial-exercise" data-label="mean4" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<script type="application/json" data-opts-chunk="1">{"fig.width":4,"fig.height":5,"fig.retina":2,"fig.align":"default","fig.keep":"high","fig.show":"asis","out.width":384,"warning":true,"error":false,"message":true,"exercise.df_print":"paged","exercise.setup":"prepare-height","exercise.checker":"NULL"}</script>
</div>
<div class="tutorial-exercise-support" data-label="mean4-hint-1" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code>#Don&#39;t forget to put a comma between the 
#arguments in your hist() function call
#
#Don&#39;t forget that R is case sensitive and
#capital and lower case letters have to match
#
#Make sure that all your opening brackets 
#have closing brackets</code></pre>
</div>
<div class="tutorial-exercise-support" data-label="mean4-hint-2" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code>#Remember that phagocytic is a variable in 
#the height data frame, so you have to refer
#to it as height$phagocytic
#
#The text for main = &quot;&quot;, xlab = &quot;&quot; and col = &quot;&quot;
#must all have quote marks at the beginning and the end</code></pre>
</div>
<div class="tutorial-exercise-support" data-label="mean4-hint-3" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code>#This is the solution:

hist(height$phagocytic,
     main = &quot;Histogram of phagocytic activity&quot;,
     xlab = &quot;Phagocytic activity&quot;,
     col = &quot;sienna3&quot;
)</code></pre>
</div>
<p>You can see that the distribution of these data has some pronounced positive skew, with the main bulk of the data having values between 100 and 200, but some values being as high as 550-600. These high values at the end of the long positive tail in the data are having a bigger effect on the mean than they are on the median, so the value of the mean is pulled up such that it no longer really indicates where the majority of the data are to be found. The median, on the other hand, is once again still giving us a indication of where most of the data are. When dealing with skewed data, therefore, it’s often better to use the median than the mean.</p>
</div>
</div>
</div>
<div id="section-measures-of-dispersion" class="section level2">
<h2>Measures of dispersion</h2>
<p>Before starting the section on the variance, here’s a video explaining how to calculate the mean and standard deviation which you might find helpful</p>
<p><img src="https://youtu.be/ChDRxxLIFMU" /></p>
<div id="section-variance" class="section level3">
<h3>Variance</h3>
<p>Let’s look at our mini-vector of data sampled from the lysozyme activity variable again. The numbers in our dataset are:</p>
<p><span class="math display">\[0.37, 0.22, 0.50, 0.53, 0.38, 0.35, 0.23\]</span> and we know that the mean is 0.37. What we want to quantify is how much spread there is in these data, or in other words how far from the mean our datapoints tend to be. We can find out how far from the mean each datapoint is by just subtracting the mean from it and then we could produce a summary of those numbers by adding them together. That’s not especially useful, however, because some of the numbers will be negative and some positive, so what we do is square each difference, which will make them all positive, and add the squared differences together.</p>
<table>
<thead>
<tr class="header">
<th align="left">Value</th>
<th align="left"><span class="math inline">\(\bar{x}\)</span></th>
<th align="left"><span class="math inline">\(x-\bar{x}\)</span></th>
<th align="left"><span class="math inline">\(\left(x-\bar{x}\right)^2\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">0.37</td>
<td align="left">0.37</td>
<td align="left">0</td>
<td align="left">0</td>
</tr>
<tr class="even">
<td align="left">0.22</td>
<td align="left">0.37</td>
<td align="left">-0.15</td>
<td align="left">0.0225</td>
</tr>
<tr class="odd">
<td align="left">0.50</td>
<td align="left">0.37</td>
<td align="left">0.13</td>
<td align="left">0.0169</td>
</tr>
<tr class="even">
<td align="left">0.53</td>
<td align="left">0.37</td>
<td align="left">0.16</td>
<td align="left">0.0256</td>
</tr>
<tr class="odd">
<td align="left">0.38</td>
<td align="left">0.37</td>
<td align="left">0.01</td>
<td align="left">0.0001</td>
</tr>
<tr class="even">
<td align="left">0.35</td>
<td align="left">0.37</td>
<td align="left">-0.02</td>
<td align="left">0.0004</td>
</tr>
<tr class="odd">
<td align="left">0.23</td>
<td align="left">0.37</td>
<td align="left">-0.14</td>
<td align="left">0.0196</td>
</tr>
</tbody>
</table>
<p>The sum of all of these squared differences is 0.0851, or to write it out formally:</p>
<p><span class="math display">\[\Sigma \left(x-\bar{x}\right)^2 = 0.0851\]</span> Remember that <span class="math inline">\(\Sigma\)</span> means “the sum of” and <span class="math inline">\(\bar{x}\)</span> is the symbol for the sample mean.</p>
<p>This quantity is called the <em>Sum of squared deviations from the mean</em> or more commonly just the <em>Sum of squares</em> and it becomes very useful when doing a very important kind of analysis called ANOVA. It’s not especially useful for our present purposes, however, because it’s not useful when you’re trying to compare how much dispersion there is between datasets. This is because it depends on the sample size: other things being equal, a variable with a sample size of 10 will have double the sum of squares of one with a sample size of 5. To account for this we could divide the sum of squares by the sample size, but in fact we divide it by something called the <em>degrees of freedom</em> which in this case is <span class="math inline">\(n-1\)</span> where <span class="math inline">\(n\)</span> is the sample size. This gives us a quantity called the <em>variance</em>, usually indicated by <span class="math inline">\(\sigma^2\)</span>, so</p>
<p><span class="math display">\[ \sigma^2 = \frac{\Sigma \left(x-\bar{x}\right)^2}{n-1} = \frac{0.0851}{6} = 0.01418\]</span> The variance is one of the most commonly used measures of how much spread there is in a data set, and we don’t need to calculate it by hand since R has a function to do it for us called <code>var()</code>, so we can calculate the variance of our 7 number subsample in R as follows:</p>
<pre class="r"><code>X1 &lt;- c(0.37, 0.22, 0.50, 0.53, 0.38, 0.35, 0.23)
var(X1)</code></pre>
<pre><code>## [1] 0.01418095</code></pre>
<p>This gratifyingly gives us the same value as when we did the calculation by hand.</p>
</div>
<div id="section-standard-deviation" class="section level3">
<h3>Standard deviation</h3>
<p>The variance is a useful measure but because it consists of the sum of the <em>squared</em> deviations from the mean it is quite hard to relate back to the original data. Simply taking the square root of the variance, however, gives us a rather more intuitive measure, the <em>standard deviation</em>. This is usually represented by <span class="math inline">\(\sigma\)</span>. For our data, the standard deviation is:</p>
<p><span class="math display">\[\sigma = \sqrt{\sigma^2} = \sqrt{0.01418} = 0.119\]</span> As with the variance, there is a built in function to calculate <span class="math inline">\(\sigma\)</span> which is <code>sd()</code>, so</p>
<pre class="r"><code>sd(X1)</code></pre>
<pre><code>## [1] 0.1190838</code></pre>
<p>The standard deviation is the average difference between a value in our data and the mean: so if you were to pick one of these data points and calculate <span class="math inline">\(x - \bar{x}\)</span>, on average the value would be 0.119. As shown in figure 2, <span class="math inline">\(\sigma\)</span> also has some special meaning when we’re dealing with normal distributions: if you think of one of those bell-shaped curves, the standard deviation is the distance from the middle to the <em>inflexion point</em> on the curve, which is where the slope stops getting steeper and starts getting shallower again. 68% (Roughly 2/3) of all the datapoints in a normally distributed dataset will be within this area. Also important is the fact that if your data are distributed following a normal distribution, 95% of all the datapoints will lie within 1.96 (roughly 2) standard deviations of the mean. That 1.96 is a bit of a magic number in statistics and crops up in all sorts of places. Finally, 99% of all the values in a normally distributed dataset will be within 2.58 standard deviations of the mean.</p>
<div class="figure">
<img src="Descriptive-statistics_files/figure-html/unnamed-chunk-7-1.png" alt="**Figure 2** Probability density of a standard normal distribution with mean=0 and standard deviation=1 showing the areas defied by the mean plus or minus 1, 1.96 and 2.58 standard deviations. The code for this figure is given at the end of the chapter." width="576" />
<p class="caption">
<strong>Figure 2</strong> Probability density of a standard normal distribution with mean=0 and standard deviation=1 showing the areas defied by the mean plus or minus 1, 1.96 and 2.58 standard deviations. The code for this figure is given at the end of the chapter.
</p>
</div>
</div>
<div id="section-interquartile-range" class="section level3">
<h3>Interquartile range</h3>
<p>The interquartile range, or IQR, is an alternative way of describing the amount of dispersion in a variable. Like the median, it relies on the use of <em>ranked</em> data. If we rank all of the data in our variable, we already know that the middle datapoint is the <em>median</em>, and that the median divides our data into two halves. If we then take only the bottom half of the data we can find the number which divides that in half, and the same with the upper half. This gives us three numbers (the <em>lower quartile</em>, the <em>median</em> and the <em>upper quartile</em>), which between them divide our data into four equal sized units.</p>
<p>Before moving on to the rest of the tutorial, here’s a short video explaining the IQR.</p>
<p><img src="https://youtu.be/uGf-DcLvA5M" /></p>
<p>Here’s an example. Let’s say we have counted the number of solitary bee burrows in 25 2m quadrats in some grassland. We can set up a vector with our data in, and then get R to rank it for us:</p>
<pre class="r"><code>counts &lt;- c(4, 1, 2, 3, 7, 0, 7, 6, 5, 1, 3, 5, 3, 13, 8, 3, 6, 3, 3, 7, 4, 6, 5, 4, 4)

counts.ranked &lt;- counts[order(counts)]

counts.ranked</code></pre>
<pre><code>##  [1]  0  1  1  2  3  3  3  3  3  3  4  4  4  4  5  5  5  6  6  6  7  7  7  8 13</code></pre>
<p>There are 25 numbers so the 13th one, 4, is the median. The 7th number (3) is the lower quartile and the 19th (6) is the upper quartile</p>
<p>0 1 1 2 3 3 <strong>3</strong> 3 3 3 4 4 <strong>4</strong> 4 5 5 5 6 <strong>6</strong> 6 7 7 7 8 13</p>
<p>You can see how these divide the data into four equal subsets. The <em>interquartile range</em> is the range between the lower and upper quartiles — in this case the IQR is 3. This is where the middle 50% of all the data are located so the interquartile range tells us how wide the spread of this middle half of the data set is.</p>
<p>R has a couple of options for calculating the <em>IQR</em>. Firstly there is the function <code>IQR()</code> which does what it says on the tin.</p>
<pre class="r"><code>IQR(counts)</code></pre>
<pre><code>## [1] 3</code></pre>
<p>Secondly, if you want to know what the values are for the quartiles rather than just the range use the <code>summary()</code> function which gives a series of useful statistics when you feed it a numerical vector:</p>
<pre class="r"><code>summary(counts)</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    0.00    3.00    4.00    4.52    6.00   13.00</code></pre>
</div>
<div id="section-measures-of-dispersion-exercises" class="section level3">
<h3>Measures of dispersion exercises</h3>
<p>Let’s go back to our data on lysozyme activity. Use <code>var()</code> and <code>sd()</code> to calculate the variance and standard deviation of these data, and then use <code>IQR()</code> to calculate the interquartile range.</p>
<div class="tutorial-exercise" data-label="spread1" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="6">
<script type="application/json" data-opts-chunk="1">{"fig.width":6.5,"fig.height":4,"fig.retina":2,"fig.align":"default","fig.keep":"high","fig.show":"asis","out.width":624,"warning":true,"error":false,"message":true,"exercise.df_print":"paged","exercise.setup":"prepare-height","exercise.checker":"NULL"}</script>
</div>
<div class="tutorial-exercise-support" data-label="spread1-hint-1" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code>#Don&#39;t forget that lysozyme is a variable within
#the height data frame, so you need to give the
#name of the data frame, then a $ symbol, then the
#name of the variable.
#
#Remember that R is case sensitive.
#</code></pre>
</div>
<div class="tutorial-exercise-support" data-label="spread1-hint-2" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code>#For the variance you need this:

var(height$lysozyme)

#you chould be able to get the sd and IQR in a similar way</code></pre>
</div>
<div class="tutorial-exercise-support" data-label="spread1-hint-3" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code>#This is the solution:

var(height$lysozyme)
sd(height$lysozyme)
IQR(height$lysozyme)</code></pre>
</div>
<p>Now use <code>summary()</code> to tell you what the values are for the quartiles and the median for the lysozyme data.</p>
<div class="tutorial-exercise" data-label="spread2" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<script type="application/json" data-opts-chunk="1">{"fig.width":6.5,"fig.height":4,"fig.retina":2,"fig.align":"default","fig.keep":"high","fig.show":"asis","out.width":624,"warning":true,"error":false,"message":true,"exercise.df_print":"paged","exercise.setup":"prepare-height","exercise.checker":"NULL"}</script>
</div>
<div class="tutorial-exercise-support" data-label="spread2-hint-1" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code>#Don&#39;t forget that lysozyme is a variable within
#the height data frame, so you need to give the
#name of the data frame, then a $ symbol, then the
#name of the variable.
#
#Remember that R is case sensitive.
#</code></pre>
</div>
<div class="tutorial-exercise-support" data-label="spread2-hint-2" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code>#This is the solution:

summary(height$lysozyme)</code></pre>
</div>
<p>Using the numbers you’ve generated, try to answer these questions</p>
<p><div class="panel-heading tutorial-quiz-title">Quiz</div><div class="panel panel-default">
<div data-label="quiz-1" class="tutorial-question panel-body">
<div id="quiz-1-answer_container" class="shiny-html-output"></div>
<div id="quiz-1-message_container" class="shiny-html-output"></div>
<div id="quiz-1-action_button_container" class="shiny-html-output"></div>
<script>if (Tutorial.triggerMathJax) Tutorial.triggerMathJax()</script>
</div>
</div><div class="panel panel-default">
<div data-label="quiz-2" class="tutorial-question panel-body">
<div id="quiz-2-answer_container" class="shiny-html-output"></div>
<div id="quiz-2-message_container" class="shiny-html-output"></div>
<div id="quiz-2-action_button_container" class="shiny-html-output"></div>
<script>if (Tutorial.triggerMathJax) Tutorial.triggerMathJax()</script>
</div>
</div></p>
<p>Now use <code>summary()</code> to find out the quartiles for the phagocytic activity variable.</p>
<div class="tutorial-exercise" data-label="spread3" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<script type="application/json" data-opts-chunk="1">{"fig.width":6.5,"fig.height":4,"fig.retina":2,"fig.align":"default","fig.keep":"high","fig.show":"asis","out.width":624,"warning":true,"error":false,"message":true,"exercise.df_print":"paged","exercise.setup":"prepare-height","exercise.checker":"NULL"}</script>
</div>
<div class="tutorial-exercise-support" data-label="spread3-hint-1" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code>#Don&#39;t forget that phagocytic is a variable within
#the height data frame, so you need to give the
#name of the data frame, then a $ symbol, then the
#name of the variable.
#
#Remember that R is case sensitive.
#</code></pre>
</div>
<div class="tutorial-exercise-support" data-label="spread3-hint-2" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code>#This is the solution:

summary(height$phagocytic)</code></pre>
</div>
<p>Look at the values for the first quartile, the median and the third quartile and think about the difference between the first quartile and the median and the median and the third quartile. Now compare that to the same values for the lysozyme data. Do you notice a pattern? I’ve summarised them in this table just to make things easier.</p>
<table>
<thead>
<tr class="header">
<th align="left">Variable</th>
<th align="left">1st quartile</th>
<th align="left">Median</th>
<th align="left">3rd quartile</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Lysozyme activity</td>
<td align="left">0.34</td>
<td align="left">0.38</td>
<td align="left">0.43</td>
</tr>
<tr class="even">
<td align="left">Phagocytic activity</td>
<td align="left">145</td>
<td align="left">170</td>
<td align="left">231</td>
</tr>
</tbody>
</table>
<p>What you should see is that the quartiles for the lysozyme data, which is approximately normally distributed, are roughly symmetrical around the median: the difference between the first quartile and the median is 0.041 whereas the difference between the median and the third quartile is 0.048. For the phagocytic activity data, however, the quartiles are not symmetrical around the median. The difference between the first quartile and the median is 25, but the difference between the median and the third quartile is 61. This is because the phagocytic activity data are strongly positively skewed, so the second quarter of the data, below the median, occupies a narrow range whereas the third quarter, above the median, has a wider range. You can see this better on a histogram.</p>
<div class="figure">
<img src="Descriptive-statistics_files/figure-html/unnamed-chunk-11-1.png" alt="**Figure 3** Frequency histograms for lysozyme activity (A) and phagocytic activity (B). The vertical lines show the quartiles and medians and the shaded boxes show the interquartile ranges." width="384" />
<p class="caption">
<strong>Figure 3</strong> Frequency histograms for lysozyme activity (A) and phagocytic activity (B). The vertical lines show the quartiles and medians and the shaded boxes show the interquartile ranges.
</p>
</div>
<p>You can see how the IQR for lysozyme activity is symmetrical, with the median in the centre, but that for phagocytic activity is not, and the median is towards the bottom end of the IQR. This is an example of why we sometimes prefer to use the median and IQR when we’re describing skewed data, because these measures can capture the shape of the data better than, for example, the mean and standard deviation. There’s lots more on this when we come to look at boxplots.</p>
<br><br>
<hr>
<p><a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/"><img alt="Creative Commons Licence" style="border-width:0" src="https://i.creativecommons.org/l/by-nc/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/">Creative Commons Attribution-NonCommercial 4.0 International License</a>.</p>

<script type="application/shiny-prerendered" data-context="server-start">
library(learnr)
knitr::opts_chunk$set(echo = TRUE)
</script>
 
<script type="application/shiny-prerendered" data-context="server">
learnr:::register_http_handlers(session, metadata = NULL)
</script>
 
<script type="application/shiny-prerendered" data-context="server">
session$onSessionEnded(function() {
        learnr:::session_stop_event(session)
      })
</script>
 
<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-mean1-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-mean1-code-editor`)), session)
output$`tutorial-exercise-mean1-output` <- renderUI({
  `tutorial-exercise-mean1-result`()
})
</script>
 
<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-mean2-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-mean2-code-editor`)), session)
output$`tutorial-exercise-mean2-output` <- renderUI({
  `tutorial-exercise-mean2-result`()
})
</script>
 
<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-mean3-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-mean3-code-editor`)), session)
output$`tutorial-exercise-mean3-output` <- renderUI({
  `tutorial-exercise-mean3-result`()
})
</script>
 
<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-mean4-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-mean4-code-editor`)), session)
output$`tutorial-exercise-mean4-output` <- renderUI({
  `tutorial-exercise-mean4-result`()
})
</script>
 
<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-spread1-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-spread1-code-editor`)), session)
output$`tutorial-exercise-spread1-output` <- renderUI({
  `tutorial-exercise-spread1-result`()
})
</script>
 
<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-spread2-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-spread2-code-editor`)), session)
output$`tutorial-exercise-spread2-output` <- renderUI({
  `tutorial-exercise-spread2-result`()
})
</script>
 
<script type="application/shiny-prerendered" data-context="server">
learnr:::question_prerendered_chunk(structure(list(type = "learnr_radio", label = "quiz-1", question = structure("Assuming our lysozyme data are normally distributed, roughly 2/3 of the data should lie between which pair of values?", html = TRUE, class = c("html", "character")), answers = list(structure(list(id = "lnr_ans_b7210d8",     option = "0.07 and 0.64", value = "0.07 and 0.64", label = structure("0.07 and 0.64", html = TRUE, class = c("html",     "character")), correct = FALSE, message = NULL), class = c("tutorial_question_answer", "tutorial_quiz_answer")), structure(list(id = "lnr_ans_897d8fc",     option = "0.37 and 0.39", value = "0.37 and 0.39", label = structure("0.37 and 0.39", html = TRUE, class = c("html",     "character")), correct = FALSE, message = NULL), class = c("tutorial_question_answer", "tutorial_quiz_answer")), structure(list(id = "lnr_ans_1bb6b73",     option = "0.22 and 0.54", value = "0.22 and 0.54", label = structure("0.22 and 0.54", html = TRUE, class = c("html",     "character")), correct = FALSE, message = NULL), class = c("tutorial_question_answer", "tutorial_quiz_answer")), structure(list(id = "lnr_ans_a20b23a",     option = "0.34 and 0.43", value = "0.34 and 0.43", label = structure("0.34 and 0.43", html = TRUE, class = c("html",     "character")), correct = FALSE, message = NULL), class = c("tutorial_question_answer", "tutorial_quiz_answer")), structure(list(id = "lnr_ans_4ca54f4",     option = "0.29 and 0.46", value = "0.29 and 0.46", label = structure("0.29 and 0.46", html = TRUE, class = c("html",     "character")), correct = TRUE, message = NULL), class = c("tutorial_question_answer", "tutorial_quiz_answer"))), button_labels = list(submit = structure("Submit Answer", html = TRUE, class = c("html", "character")), try_again = structure("Try Again", html = TRUE, class = c("html", "character"))), messages = list(correct = structure("Correct!", html = TRUE, class = c("html", "character")), try_again = structure("Incorrect", html = TRUE, class = c("html", "character")), incorrect = structure("Incorrect", html = TRUE, class = c("html", "character")), message = NULL, post_message = NULL), ids = list(    answer = "quiz-1-answer", question = "quiz-1"), loading = structure("<strong>Loading:<\u002fstrong> \nAssuming our lysozyme data are normally distributed, roughly 2/3 of the data should lie between which pair of values?\n<br/><br/><br/>", html = TRUE, class = c("html", "character")), random_answer_order = FALSE, allow_retry = FALSE,     seed = 9927010.99537737, options = list()), class = c("learnr_radio", "tutorial_question")))
</script>
 
<script type="application/shiny-prerendered" data-context="server">
learnr:::question_prerendered_chunk(structure(list(type = "learnr_radio", label = "quiz-2", question = structure("If you were to rank the lysozyme data and divide it into four equal parts, which numbers would give you the range for the top quarter of the data (i.e. the part with the largest values)?", html = TRUE, class = c("html", "character")), answers = list(structure(list(id = "lnr_ans_f9e53fb",     option = "0.38 and 0.43", value = "0.38 and 0.43", label = structure("0.38 and 0.43", html = TRUE, class = c("html",     "character")), correct = FALSE, message = NULL), class = c("tutorial_question_answer", "tutorial_quiz_answer")), structure(list(id = "lnr_ans_44a332c",     option = "0.43 and 0.64", value = "0.43 and 0.64", label = structure("0.43 and 0.64", html = TRUE, class = c("html",     "character")), correct = TRUE, message = NULL), class = c("tutorial_question_answer", "tutorial_quiz_answer")), structure(list(id = "lnr_ans_45b7e19",     option = "0.34 and 0.38", value = "0.34 and 0.38", label = structure("0.34 and 0.38", html = TRUE, class = c("html",     "character")), correct = FALSE, message = NULL), class = c("tutorial_question_answer", "tutorial_quiz_answer")), structure(list(id = "lnr_ans_bb1c6f4",     option = "0.07 and 0.64", value = "0.07 and 0.64", label = structure("0.07 and 0.64", html = TRUE, class = c("html",     "character")), correct = FALSE, message = NULL), class = c("tutorial_question_answer", "tutorial_quiz_answer")), structure(list(id = "lnr_ans_54ca610",     option = "0.38 and 0.64", value = "0.38 and 0.64", label = structure("0.38 and 0.64", html = TRUE, class = c("html",     "character")), correct = FALSE, message = NULL), class = c("tutorial_question_answer", "tutorial_quiz_answer"))), button_labels = list(submit = structure("Submit Answer", html = TRUE, class = c("html", "character")), try_again = structure("Try Again", html = TRUE, class = c("html", "character"))), messages = list(correct = structure("Correct!", html = TRUE, class = c("html", "character")), try_again = structure("Incorrect", html = TRUE, class = c("html", "character")), incorrect = structure("Incorrect", html = TRUE, class = c("html", "character")), message = NULL, post_message = NULL), ids = list(    answer = "quiz-2-answer", question = "quiz-2"), loading = structure("<strong>Loading:<\u002fstrong> \nIf you were to rank the lysozyme data and divide it into four equal parts, which numbers would give you the range for the top quarter of the data (i.e. the part with the largest values)?\n<br/><br/><br/>", html = TRUE, class = c("html", "character")), random_answer_order = FALSE, allow_retry = FALSE,     seed = 1632962405.23959, options = list()), class = c("learnr_radio", "tutorial_question")))
</script>
 
<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-spread3-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-spread3-code-editor`)), session)
output$`tutorial-exercise-spread3-output` <- renderUI({
  `tutorial-exercise-spread3-result`()
})
</script>
 <!--html_preserve-->
<script type="application/shiny-prerendered" data-context="dependencies">
{"type":"list","attributes":{},"value":[{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["jquery"]},{"type":"character","attributes":{},"value":["1.11.3"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/jquery"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["jquery.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.4"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["bootstrap"]},{"type":"character","attributes":{},"value":["3.3.5"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/bootstrap"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["viewport"]}},"value":[{"type":"character","attributes":{},"value":["width=device-width, initial-scale=1"]}]},{"type":"character","attributes":{},"value":["js/bootstrap.min.js","shim/html5shiv.min.js","shim/respond.min.js"]},{"type":"character","attributes":{},"value":["css/bootstrap.min.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.4"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["pagedtable"]},{"type":"character","attributes":{},"value":["1.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/pagedtable-1.1"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["js/pagedtable.js"]},{"type":"character","attributes":{},"value":["css/pagedtable.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.4"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["highlightjs"]},{"type":"character","attributes":{},"value":["9.12.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/highlightjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["highlight.js"]},{"type":"character","attributes":{},"value":["textmate.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.4"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial"]},{"type":"character","attributes":{},"value":["0.10.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial.js"]},{"type":"character","attributes":{},"value":["tutorial.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial-autocompletion"]},{"type":"character","attributes":{},"value":["0.10.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial-autocompletion.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial-diagnostics"]},{"type":"character","attributes":{},"value":["0.10.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial-diagnostics.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial-format"]},{"type":"character","attributes":{},"value":["0.10.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmarkdown/templates/tutorial/resources"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial-format.js"]},{"type":"character","attributes":{},"value":["tutorial-format.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["jquery"]},{"type":"character","attributes":{},"value":["1.11.3"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/jquery"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["jquery.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.4"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["navigation"]},{"type":"character","attributes":{},"value":["1.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/navigation-1.1"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tabsets.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.4"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["highlightjs"]},{"type":"character","attributes":{},"value":["9.12.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/highlightjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["highlight.js"]},{"type":"character","attributes":{},"value":["default.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.4"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["jquery"]},{"type":"character","attributes":{},"value":["1.11.3"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/jquery"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["jquery.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.4"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["font-awesome"]},{"type":"character","attributes":{},"value":["5.1.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/fontawesome"]}]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["css/all.css","css/v4-shims.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.4"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["bootbox"]},{"type":"character","attributes":{},"value":["4.4.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/bootbox"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["bootbox.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["idb-keyvalue"]},{"type":"character","attributes":{},"value":["3.2.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/idb-keyval"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["idb-keyval-iife-compat.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[false]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial"]},{"type":"character","attributes":{},"value":["0.10.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial.js"]},{"type":"character","attributes":{},"value":["tutorial.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial-autocompletion"]},{"type":"character","attributes":{},"value":["0.10.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial-autocompletion.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial-diagnostics"]},{"type":"character","attributes":{},"value":["0.10.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial-diagnostics.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]}]}
</script>
<!--/html_preserve-->
<!--html_preserve-->
<script type="application/shiny-prerendered" data-context="execution_dependencies">
{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["packages"]}},"value":[{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["packages","version"]},"class":{"type":"character","attributes":{},"value":["data.frame"]},"row.names":{"type":"integer","attributes":{},"value":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39]}},"value":[{"type":"character","attributes":{},"value":["backports","base","checkmate","compiler","datasets","digest","ellipsis","evaluate","fastmap","graphics","grDevices","highr","htmltools","htmlwidgets","httpuv","jsonlite","knitr","later","learnr","magrittr","markdown","methods","mime","promises","R6","Rcpp","rlang","rmarkdown","rprojroot","shiny","stats","stringi","stringr","tools","utils","withr","xfun","xtable","yaml"]},{"type":"character","attributes":{},"value":["1.1.10","4.0.2","2.0.0","4.0.2","4.0.2","0.6.25","0.3.1","0.14","1.0.1","4.0.2","4.0.2","0.8","0.5.0","1.5.1","1.5.4","1.7.1","1.30","1.1.0.1","0.10.1","1.5","1.1","4.0.2","0.9","1.1.1","2.4.1","1.0.5","0.4.7","2.4","1.3-2","1.5.0","4.0.2","1.5.3","1.4.0","4.0.2","4.0.2","2.3.0","0.18","1.8-4","2.2.1"]}]}]}
</script>
<!--/html_preserve-->
</div>
</div>

</div> <!-- topics -->

<div class="topicsContainer">
<div class="topicsPositioner">
<div class="band">
<div class="bandContent topicsListContainer">

<!-- begin doc-metadata -->
<div id="doc-metadata">
<h2 class="title toc-ignore" style="display:none;">Descriptive and Exploratory Statistics 2: Descriptive statistics</h2>
<h4 class="author"><em>Rob Knell</em></h4>
</div>
<!-- end doc-metadata -->

</div> <!-- bandContent.topicsListContainer -->
</div> <!-- band -->
</div> <!-- topicsPositioner -->
</div> <!-- topicsContainer -->


</div> <!-- bandContent page -->
</div> <!-- pageContent band -->




<script>
// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});
</script>


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>


</body>

</html>
