<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />

<meta name="author" content="Rob Knell" />


<meta name="progressive" content="false" />
<meta name="allow-skip" content="false" />

<title>Sampling and uncertainty 1: Sampling distributions</title>


<!-- highlightjs -->
<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>

<!-- taken from https://github.com/rstudio/rmarkdown/blob/67b7f5fc779e4cfdfd0f021d3d7745b6b6e17149/inst/rmd/h/default.html#L296-L362 -->
<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<script>
$(document).ready(function () {
  window.buildTabsets("section-TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>
<!-- end tabsets -->


<link rel="stylesheet" href="http://research.sbcs.qmul.ac.uk/r.knell/learnr_data/test2.css" type="text/css" />

</head>

<body>



<div class="pageContent band">
<div class="bandContent page">

<div class="topics">

<div id="section-welcome" class="section level2">
<h2>Welcome</h2>
<p>Welcome to the sampling and uncertainty tutorials. These aim to teach how we quantify uncertainty in statistics via understanding sampling distributions, standard errors and confidence intervals. There are four tutorials in total and each builds on the previous one. There is some knowledge of R assumed: if you are unhapy with concepts such as arguments in functions, saving data into vectors etc. then you should probably review these before attempting these.</p>
</div>
<div id="section-introduction" class="section level2">
<h2>Introduction</h2>
<p>There’s a fundamental problem in much of science which revolves around the simple fact that we are usually unable to measure all of the things we would like to measure. Let’s say you’re a climate change biologist and you’re concerned that chinstrap penguin populations in Antarctica might be negatively impacted by rising temperatures because the availability of krill, their main food, will decline as the temperature increases. To monitor this you want to know how much the penguins in your population weigh at the start of the reproductive season, so that you can see if their mean weight is declining over time. There are estimated to be around 8 million chinstrap penguins on the planet, and in your study population there are around 55,000 breeding pairs, so a total population of somewhere above 110,000. It’s next to impossible to catch and weigh 110,000 penguins, of course, so what you would do would be to weigh a smaller number, maybe 30, maybe 100, maybe 500 depending on the availability of people, time, and equipment for penguin capture and and weighing. This group of penguins represents a <em>sample</em> of the total <em>population</em>. What you are trying to find out is the mean weight for the population, the <em>population mean</em> (<span class="math inline">\(\mu\)</span>) and the hope is that the mean weight of the penguins in your sample (the <em>sample mean</em>, <span class="math inline">\(\bar{x}\)</span>) is sufficiently close to the mean weight of all the penguins in your population to be a useful number.</p>
<p><img src="images/chinstrap.jpg" width="400" alt="Chinstrap penguin" /> Chinstrap penguin on Deception island. Photo Christopher Michel, released on a creative commons CC BY 2.0 licence.</p>
<p>Assuming you’ve managed to avoid any bias in your sampling, you still have to think about how representative your sample mean is likely to be of the true population mean. Because of chance events in the sampling process, a completely random sample will usually be different from the population it’s sampled from in some way. In our penguin example you might have a bigger proportion of heavy or light penguins in your sample than in the population, giving you a sample mean that is too high or too low.</p>
<p>There is, then, <em>uncertainty</em> regarding how representative a sample mean is of the population mean, and it’s important to be able to measure this uncertainty in some way: you need to know whether the mean that you’ve produced is likely to be a good estimate of the population mean or not. This series of tutorials teaches a series of important concepts related to this: sampling distributions, standard errors and confidence intervals. These are the ideas and tools that statisticians use to describe and quantify the amount of uncertainty associated with a particular estimate.</p>
</div>
<div id="section-the-sampling-distribution-of-the-mean" class="section level2">
<h2>The sampling distribution of the mean</h2>
<p>To try to understand how your sample mean might deviate from the population mean we need to think about the possible outcomes when you sample from a given population. As another example, let’s say you want to know what the average systolic blood pressure is for women between 20 and 30 years old in the UK. Measuring the blood pressure of every woman aged between 20 and 30 in a population of 66 million people would take a long time, however, so as with our penguins what you would do instead is sample from the population: select a smaller number of individuals at random, measure them and hope that the value you calculate from your sample (the sample mean, denoted by <span class="math inline">\(\bar{x}\)</span>) is sufficiently similar to the population mean (denoted by <span class="math inline">\(\mu\)</span>) to give you a good idea of what the population level value is. We can simulate this using R’s excellent random number generation tools. The <code>rnorm()</code> function generates values drawn from a normal distribution with a specified standard deviation and mean, with the arguments for the function being <code>n =</code> for the sample size, <code>mean =</code> for the mean and <code>sd =</code> for the standard deviation. Here I’ve used <code>rnorm()</code> to generate 30 numbers from a normal distribution with <code>mean = 120</code> and <code>sd = 17</code> which is close to what we might see in women of the age class we’re interested in.</p>
<pre class="r"><code># Set the random number seed so we get the same
# result each time
set.seed(10)

# Generate sample and save as a vector
# called sample1
sample1 &lt;- rnorm(n = 30,
                 mean = 120,
                 sd = 17)

# Round the values off to 1 decimal place
sample1 &lt;- round(sample1, 1)

# Show us the numbers!
print(sample1)</code></pre>
<pre><code>##  [1] 120.3 116.9  96.7 109.8 125.0 126.6  99.5 113.8  92.3 115.6 138.7 132.8
## [13] 116.0 136.8 132.6 121.5 103.8 116.7 135.7 128.2 109.9  82.9 108.5  84.0
## [25]  98.5 113.6 108.3 105.2 118.3 115.7</code></pre>
<p>What’s the mean of our sample? See if you can calculate it using the <code>mean()</code> function.</p>
<div class="tutorial-exercise-support" data-label="mean1-setup" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code>set.seed(10)

# Generate sample and save as a vector
# called sample1
sample1 &lt;- rnorm(n = 30,
                 mean = 120,
                 sd = 17)

# Round the values off to 1 decimal place
sample1 &lt;- round(sample1, 1)</code></pre>
</div>
<div class="tutorial-exercise" data-label="mean1" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<script type="application/json" data-opts-chunk="1">{"fig.width":6.5,"fig.height":4,"fig.retina":2,"fig.align":"default","fig.keep":"high","fig.show":"asis","out.width":624,"warning":true,"error":false,"message":true,"exercise.df_print":"paged","exercise.checker":"NULL"}</script>
</div>
<div class="tutorial-exercise-support" data-label="mean1-hint-1" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code># You just need to put the name of the vector
# (sample1) as an argument for the mean() function</code></pre>
</div>
<div class="tutorial-exercise-support" data-label="mean1-hint-2" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code># This is the solution

mean(sample1)</code></pre>
</div>
<p>So we simulated sampling 30 individuals from a population with a population mean of 120, and our sample mean is 114.7. That’s somewhat close to the actual population mean but purely by random chance we got more low values than high values in our sample and so our sample mean underestimates the population mean by 5.3 mmHg. If you were to do this exercise with in the real world, however, you would have no idea at all how representative your sample mean was. It could be exactly right, it could be slightly low, it could be much, much too high. What about taking a second sample? This code is very similar to the previous exercise, but there are three mistakes that mean it won’t run as it is. See if you can fix them.</p>
<div class="tutorial-exercise" data-label="mean2" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="15">
<pre class="text"><code>set.seed(2)

# Generate sample and save as a vector
# called sample1
sample2 &lt;- rnorm(n = 30,
                 mean = 120
                 sd = 17)

# Round the values off to 1 decimal place
sample2 &lt;- round(sample1, 1

# Calculate the mean
mean(sample2)</code></pre>
<script type="application/json" data-opts-chunk="1">{"fig.width":6.5,"fig.height":4,"fig.retina":2,"fig.align":"default","fig.keep":"high","fig.show":"asis","out.width":624,"warning":true,"error":false,"message":true,"exercise.df_print":"paged","exercise.checker":"NULL"}</script>
</div>
<div class="tutorial-exercise-support" data-label="mean2-hint-1" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code># Check that all the arguments are separated by commas</code></pre>
</div>
<div class="tutorial-exercise-support" data-label="mean2-hint-2" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code># Check that all the arguments are separated by commas
# 
# Check that all the brackets pair up
#
# Check that all the object names are correct</code></pre>
</div>
<div class="tutorial-exercise-support" data-label="mean2-hint-3" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code># Check that all the arguments are separated by commas
# 
# There&#39;s a missing comma in the rnorm(... function call
# 
# Check that all the brackets pair up
# 
# There&#39;s a missing bracket in the round(... function call 
#
# Check that all the object names are correct
#
# There&#39;s a mis-named object in the round(... function call </code></pre>
</div>
<div class="tutorial-exercise-support" data-label="mean2-hint-4" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code># This is the solution:

set.seed(2)

# Generate sample and save as a vector
# called sample1
sample2 &lt;- rnorm(n = 30,
                 mean = 120,
                 sd = 17)

# Round the values off to 1 decimal place
sample2 &lt;- round(sample2, 1)

# Calculate the mean
mean(sample2)</code></pre>
</div>
<p>This time our sample mean overestimates the population mean somewhat, so the random number generator, purely by chance, gave us more high values. The value we obtained from the second sample is different from the first one simply because we have sampled (or simulated sampling) a separate set of individuals and they will not all have the same blood pressures as the women in the first sample. Now we have a somewhat better idea of what the real population mean might be: we took two samples of thirty, one of which gave a mean of 114.7 and one a mean of 123.9. You might now be a bit more confident that the true value of the mean lies somewhere in the region of these two values.</p>
<p>Now think about what would happen if you repeated this many times, maybe a hundred. You select 30 women from the population, measure their blood pressure and calculate a mean, then you do it again 99 more times. Obviously no one would actually do this, but if you did you would generate a dataset of 100 sample means. Some of these would be very close to the actual population mean, but some would not: simply by chance in one sample you might get a lot of people with rather high blood pressure, meaning that your sample mean was rather higher than the population mean, or you might get several people with very low blood pressure leading to a low estimate. If you were to plot a frequency histogram of your 100 means it might look like this:</p>
<pre class="r"><code>#Set random number seed
set.seed(20)  

#Generate the means of 100 samples of 30
#datapoints each, drawn from a normal 
#distribution with mean 120 and sd 17
samples &lt;-  
  replicate(n = 100, mean(rnorm(
    n = 30, mean = 120, sd = 17
  )))

#Plot frequency histogram of means
hist(samples,
     breaks = 20,
     xlab = &quot;Mean systolic blood pressure (mm Hg)&quot;,
     main = &quot;Frequency histogram for 100 blood \npressure samples&quot;)</code></pre>
<p><img src="Sampling-distributions_files/figure-html/unnamed-chunk-2-1.png" width="624" /></p>
<p>We can see that the majority of our sample means are relatively close to the true population mean of 120 mm Hg, but some are not. The distribution overall is roughly symmetrical as you might expect, with about the same number of high values as low values. What might this look like if we increased our sample size from 100 to 10000? Here’s the code we used before, try to change it to have a sample of 10000 means instead of 100.</p>
<div class="tutorial-exercise" data-label="sampling1" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="20">
<pre class="text"><code>#Set random number seed
set.seed(20)  

#Generate the means of 100 samples of 30
#datapoints each, drawn from a normal 
#distribution with mean 120 and sd 17
samples &lt;-  
  replicate(n = 100, mean(rnorm(
    n = 30, mean = 120, sd = 17
  )))

#Plot frequency histogram of means
hist(samples,
     breaks = 20,
     xlab = &quot;Mean systolic blood pressure (mm Hg)&quot;,
     main = &quot;Frequency histogram for 100 blood\npressure samples&quot;)</code></pre>
<script type="application/json" data-opts-chunk="1">{"fig.width":6.5,"fig.height":4,"fig.retina":2,"fig.align":"default","fig.keep":"high","fig.show":"asis","out.width":624,"warning":true,"error":false,"message":true,"exercise.df_print":"paged","exercise.checker":"NULL"}</script>
</div>
<div class="tutorial-exercise-support" data-label="sampling1-hint-1" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code>#This is very simple: just change the 
#&quot;n = 100&quot; argument in the replicate() function call
#You probably want to change the title as well</code></pre>
</div>
<div class="tutorial-exercise-support" data-label="sampling1-hint-2" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code>#This is the solution

#Set random number seed
set.seed(20)  

#Generate the means of 100 samples of 30
#datapoints each, drawn from a normal 
#distribution with mean 120 and sd 17
samples &lt;-  
  replicate(n = 10000, mean(rnorm(
    n = 30, mean = 120, sd = 17
  )))

#Plot frequency histogram of means
hist(samples,
     breaks = 20,
     xlab = &quot;Mean systolic blood pressure&quot;,
     main = &quot;Frequency histogram for 10000 blood pressure samples&quot;)</code></pre>
</div>
<p>Now you can really see the pattern in our distribution of means. The shape of this histogram should be familiar to you because it follows a <em>normal distribution</em> and you can clearly see that famous bell curve. If we repeatedly sample from the same population, and calculate a mean for each sample, therefore, it seems that the distribution of means follows a normal distribution, centred around the population mean. Recall that our aim is to quantify how accurate an estimate of the population mean our sample mean is likely to be, and have another look at this histogram. Knowing the shape of this <em>sampling distribution</em> of means tells us that any individual sample mean is most likely to be where the bulk of our means are located, so between about 117 and 123 mm Hg, or in other words within about 3mm Hg of the true population mean.</p>
</div>
<div id="section-sampling-distributions-of-means-from-non-normal-populations" class="section level2">
<h2>Sampling distributions of means from non-normal populations</h2>
<p>What if we don’t sample from a normal distribution though? What might this <em>sampling distribution</em> of means look like if we drew them from a population with a distribution that didn’t itself follow that bell curve?</p>
<p>The <code>runif()</code> function in R draws numbers from a <em>uniform</em> distribution — an even distribution lying between a maximum and a minimum. The arguments it takes are <code>n =</code> for the sample size, <code>min =</code> to define the minimum value and <code>max =</code> to define the maximum. Here’s some example data generated by <code>runif()</code>:</p>
<pre class="r"><code># Generate random numbers fdrawn from uniform distirbution
samples &lt;- runif(n = 120, 
                 min = 0, 
                 max = 100)

# Draw histogram
# NB the \n in the main = argument is an &#39;escape character&quot;
# which tells R to put a new line in the text at that point

hist(samples,
     breaks = 20,
     xlab = &quot;Value&quot;,
     main = &quot;Frequency histogram for 120 numbers drawn\nat random from a uniform distribution&quot;)</code></pre>
<p><img src="Sampling-distributions_files/figure-html/unnamed-chunk-3-1.png" width="624" /></p>
<p>As you can see, the data in this single sample are distributed fairly evenly across the whole range. Some of our bins have a few more datapoints than others, but overall there’s no overall pattern. What happens if we use <code>runif()</code> to sample repeatedly from a uniform distribution and plot a frequency histogram of how our means are distributed? See if you can modify the code we used earlier to replace the <code>rnorm()</code> function generating the data we saw before with <code>runif()</code>, with a sample size of 30, a minimum of 105 and a maximum of 135. It’s probably a good idea to change the title of the histogram to reflect what you’re doing.</p>
<div class="tutorial-exercise" data-label="sampling2" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="20">
<pre class="text"><code>#Set random number seed
set.seed(20)  

#Generate the means of 100 samples of 30
#datapoints each, drawn from a normal 
#distribution with mean 120 and sd 17
samples &lt;-  
  replicate(n = 10000, 
  mean(rnorm(n = 30, mean = 120, sd = 17)
       ))

#Plot frequency histogram of means
hist(samples,
     breaks = 20,
     xlab = &quot;Values&quot;,
     main = &quot;Frequency histogram for 100 blood pressure samples&quot;)</code></pre>
<script type="application/json" data-opts-chunk="1">{"fig.width":6.5,"fig.height":4,"fig.retina":2,"fig.align":"default","fig.keep":"high","fig.show":"asis","out.width":624,"warning":true,"error":false,"message":true,"exercise.df_print":"paged","exercise.checker":"NULL"}</script>
</div>
<div class="tutorial-exercise-support" data-label="sampling2-hint-1" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code># What you need to change is the 
# rnorm(n = 30, mean = 120, sd = 17)
# part in the lines of code which begin
# &quot;samples &lt;-&quot; </code></pre>
</div>
<div class="tutorial-exercise-support" data-label="sampling2-hint-2" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code># What you need to change is the 
# rnorm(n = 30, mean = 120, sd = 17)
# part in the samples &lt;- lines of code

#You need to replace it with 
runif(n = 30, min = 105, max = 135)</code></pre>
</div>
<div class="tutorial-exercise-support" data-label="sampling2-hint-3" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code>#What you need to change is the 
# rnorm(n = 30, mean = 120, sd = 17)
# part in the samples &lt;- lines of code

#You need to replace it with 
# runif(n = 30, min = 105, max = 135)

# Make sure all the arguments are 
# separated by commas and that all 
# the brackets match</code></pre>
</div>
<div class="tutorial-exercise-support" data-label="sampling2-hint-4" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code>#This is the solution

#Set random number seed
set.seed(20)  

#Generate the means of 100 samples of 30
#datapoints each, drawn from a normal 
#distribution with mean 120 and sd 17
samples &lt;-  
  replicate(n = 10000, 
  mean(runif(n = 30, min = 105, max = 135)
       ))

#Plot frequency histogram of means
hist(samples,
     breaks = 20,
     xlab = &quot;Values&quot;,
     main = &quot;Frequency histogram for the means of 10000 samples\nfrom a uniform distribution&quot;)</code></pre>
</div>
<p>This histogram looks almost identical to the previous one where the means were generated from data drawn from a normal distribution, even though the population the data were drawn from this time had a distribution that in no way resembles a normal distribution. This illustrates a hugely important point:</p>
<blockquote>
<p>If you sample repeatedly from the same population, as the number of samples increases <strong>the sampling distribution of the means will always tend towards a normal distribution</strong> with the mean of the sampling distribution tending to get closer to the population mean as the number of samples increases. For very large numbers of samples the sampling distribution of the means will be normal, and the mean for the sampling distribution will be the same as the population mean.</p>
</blockquote>
</div>
<div id="section-the-effect-of-the-size-of-each-sample" class="section level2">
<h2>The effect of the size of each sample</h2>
<p>OK, so if we sample repeatedly and calculate lots of means the frequency distribution for those means will always tend towards a normal distribution, no matter what the underlying distribution. What if we increase the sample size each of those means is calculated from? Instead of taking 10000 samples of 30 values each and calculating a mean for each, what happens if we take 10000 samples of 100 values each and calculate a mean for each.</p>
<p>Here’s some code that will draw two sets of samples from the same normal distribution and draw two histograms. The part of the code beginning with <code>samples2 &lt;-</code> needs to be filled in. Use the code from the <code>samples &lt;-</code> lines but change it so that each mean is calculated from 100 values instead of 30. For the two histograms, we want them to be drawn with the same x-axis scaling so you’ll need to add the argument <code>xlim = c(105, 135)</code> to the code for each one, and you’ll want to change the titles as well to reflect what you’re plotting.</p>
<div class="tutorial-exercise" data-label="sampling3" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="35">
<pre class="text"><code>#Draw two plots one above the other
par(mfrow = c(2,1))

#Set random number seed
set.seed(20)  

#Generate the means of 100 samples of 30
#datapoints each, drawn from a normal 
#distribution with mean 120 and sd 17
samples &lt;-  
  replicate(n = 10000, 
  mean(rnorm(n = 30, mean = 120, sd = 17)
       ))

#This is the bit you need to complete
samples2 &lt;-

#Plot frequency histogram of means
hist(samples,
     breaks = 20,
     xlab = &quot;Mean systolic blood pressure&quot;,
     main = &quot;Frequency histogram for 10000 blood pressure samples&quot;)

#Plot frequency histogram of means
hist(samples2,
     breaks = 20,
     xlab = &quot;Mean systolic blood pressure&quot;,
     main = &quot;Frequency histogram for 10000 blood pressure samples&quot;)</code></pre>
<script type="application/json" data-opts-chunk="1">{"fig.width":6.5,"fig.height":8,"fig.retina":2,"fig.align":"default","fig.keep":"high","fig.show":"asis","out.width":624,"warning":true,"error":false,"message":true,"exercise.df_print":"paged","exercise.checker":"NULL"}</script>
</div>
<div class="tutorial-exercise-support" data-label="sampling3-hint-1" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code># Use the code from 

samples &lt;-  
  replicate(n = 10000, 
  mean(rnorm(n = 30, mean = 120, sd = 17)
       ))

#starting with replicate. Change the sample size 
#in the rnorm() function call to 100</code></pre>
</div>
<div class="tutorial-exercise-support" data-label="sampling3-hint-2" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code># You only need to change 1 number,
# the n = 30, from the rnorm function call
# need to be changed to n = 100,

# For the xlim = c(105, 135) arguments just add 
# this code in for each one</code></pre>
</div>
<div class="tutorial-exercise-support" data-label="sampling3-hint-3" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code># Make sure all the arguments are 
# separated by commas and that all 
# the brackets match</code></pre>
</div>
<div class="tutorial-exercise-support" data-label="sampling3-hint-4" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code># This is the solution


#Draw two plots one above the other
par(mfrow = c(2,1))

#Set random number seed
set.seed(20)  

#Generate the means of 100 samples of 30
#datapoints each, drawn from a normal 
#distribution with mean 120 and sd 17
samples &lt;-  
  replicate(n = 10000, 
  mean(rnorm(n = 30, mean = 120, sd = 17)
       ))

#This is the bit you need to complete
samples2 &lt;-
    replicate(n = 10000, 
  mean(rnorm(n = 100, mean = 120, sd = 17)
       ))

#Plot frequency histogram of means
hist(samples,
     breaks = 20,
     xlim  =c(105, 135),
     xlab = &quot;Mean systolic blood pressure&quot;,
     main = &quot;Sample size  = 30&quot;)

#Plot frequency histogram of means
hist(samples2,
     breaks = 20,
     xlim  =c(105, 135),
     xlab = &quot;Mean systolic blood pressure&quot;,
     main = &quot;Sample size  = 100&quot;)</code></pre>
</div>
<p>What you can see is that when the mean for each sample is calculated from more data, the amount of spread in the sampling distribution of means is lower: there are fewer sample means with very high or very low values. This makes sense of course: the larger the sample used to calculate the sample mean, the more accurate an estimate of the population mean it is likely to be.</p>
</div>
<div id="section-how-does-the-variance-of-the-population-affect-the-sampling-distribution" class="section level2">
<h2>How does the variance of the population affect the sampling distribution?</h2>
<p>Something else that might influence our sampling distribution is the amount of variability in the population that is being sampled from. Let’s repeat the previous exercise but instead of changing the sample size for the second histogram try to change the standard deviation of the population being sampled from 17 to 10. We need to plot our histograms on the same x-axis scale so you need to add the argument <code>xlim = c(105, 135)</code> to each <code>hist()</code> function call.</p>
<div class="tutorial-exercise" data-label="sampling4" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="35">
<pre class="text"><code>#Draw two plots one above the other
par(mfrow = c(2,1))

#Set random number seed
set.seed(20)  

#Generate the means of 100 samples of 30
#datapoints each, drawn from a normal 
#distribution with mean 120 and sd 17
samples &lt;-  
  replicate(n = 10000, 
  mean(rnorm(n = 30, mean = 120, sd = 17)
       ))

#This is the bit you need to complete
samples2 &lt;-

#Plot frequency histogram of means
hist(samples,
     breaks = 20,
     xlab = &quot;Mean systolic blood pressure&quot;,
     main = &quot;Frequency histogram for 10000 blood pressure samples&quot;)

#Plot frequency histogram of means
hist(samples2,
     breaks = 20,
     xlab = &quot;Mean systolic blood pressure&quot;,
     main = &quot;Frequency histogram for 10000 blood pressure samples&quot;)</code></pre>
<script type="application/json" data-opts-chunk="1">{"fig.width":6.5,"fig.height":6,"fig.retina":2,"fig.align":"default","fig.keep":"high","fig.show":"asis","out.width":624,"warning":true,"error":false,"message":true,"exercise.df_print":"paged","exercise.checker":"NULL"}</script>
</div>
<div class="tutorial-exercise-support" data-label="sampling4-hint-1" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code># Use the code from 

samples &lt;-  
  replicate(n = 10000, 
  mean(rnorm(n = 30, mean = 120, sd = 17)
       ))

#starting with replicate. Change the 
#standard deviation (sd)
#in the rnorm() function call to 7</code></pre>
</div>
<div class="tutorial-exercise-support" data-label="sampling4-hint-2" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code># You only need to change 1 number,
# the n = 30, from the rnorm function call
# need to be changed to n = 100,

# For the xlim = c(105, 135) arguments just add 
# this code in for each one</code></pre>
</div>
<div class="tutorial-exercise-support" data-label="sampling4-hint-3" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code># Make sure all the arguments are 
# separated by commas and that all 
# the brackets match</code></pre>
</div>
<div class="tutorial-exercise-support" data-label="sampling4-hint-4" data-caption="Code" data-completion="1" data-diagnostics="1" data-startover="1" data-lines="0">
<pre class="text"><code># This is the solution


#Draw two plots one above the other
par(mfrow = c(2,1))

#Set random number seed
set.seed(20)  

#Generate the means of 100 samples of 30
#datapoints each, drawn from a normal 
#distribution with mean 120 and sd 17
samples &lt;-  
  replicate(n = 10000, 
  mean(rnorm(n = 30, mean = 120, sd = 17)
       ))

#This is the bit you need to complete
samples2 &lt;-
    replicate(n = 10000, 
  mean(rnorm(n = 100, mean = 120, sd = 10)
       ))

#Plot frequency histogram of means
hist(samples,
     breaks = 20,
     xlim  =c(105, 135),
     xlab = &quot;Mean systolic blood pressure&quot;,
     main = &quot;Standard deviation  = 17&quot;)

#Plot frequency histogram of means
hist(samples2,
     breaks = 20,
     xlim  =c(105, 135),
     xlab = &quot;Mean systolic blood pressure&quot;,
     main = &quot;Standard deviation  = 10&quot;)</code></pre>
</div>
<p>The second histogram shows that when samples are taken from a population with a lower standard deviation, the sampling distribution of the means is similarly reduced. This makes sense: if the individuals in the population are not especially variable then those in the sample are unlikely to show much variability, and <em>vice-versa</em>.</p>
</div>
<div id="section-summary-and-quiz" class="section level2">
<h2>Summary and quiz</h2>
<p>What are the take-home messages from this? We know how sample means are likely to be distributed around population means, and we’ve seen that larger sample sizes and lower dispersion in the population being sampled will both lead to sample means that, on average, are closer to population means. If we want to quantify how certain we are, one option would be to repeartedly sample and to use the sampling distribution of means to tell us what the real population mean is likely to be. That’s not usually going to be an option, however, but what we can do is use what we’ve found out in this tutorial to help us to quantify uncertainty for a single sample — this takes us to the next tutorial, on standard errors.</p>
<p>We’ll finish up with a short quiz to see if you’ve managed to grasp the main points so far.</p>
<div class="panel-heading tutorial-quiz-title">Quiz</div><div class="panel panel-default">
<div data-label="quiz-1" class="tutorial-question panel-body">
<div id="quiz-1-answer_container" class="shiny-html-output"></div>
<div id="quiz-1-message_container" class="shiny-html-output"></div>
<div id="quiz-1-action_button_container" class="shiny-html-output"></div>
<script>if (Tutorial.triggerMathJax) Tutorial.triggerMathJax()</script>
</div>
</div><div class="panel panel-default">
<div data-label="quiz-2" class="tutorial-question panel-body">
<div id="quiz-2-answer_container" class="shiny-html-output"></div>
<div id="quiz-2-message_container" class="shiny-html-output"></div>
<div id="quiz-2-action_button_container" class="shiny-html-output"></div>
<script>if (Tutorial.triggerMathJax) Tutorial.triggerMathJax()</script>
</div>
</div> <br><br>
<hr>
<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/"><img alt="Creative Commons Licence" style="border-width:0" src="https://i.creativecommons.org/l/by-nc/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/">Creative Commons Attribution-NonCommercial 4.0 International License</a>. 
<script type="application/shiny-prerendered" data-context="server-start">
library(learnr)
knitr::opts_chunk$set(echo = TRUE)
</script>
 
<script type="application/shiny-prerendered" data-context="server">
learnr:::register_http_handlers(session, metadata = NULL)
</script>
 
<script type="application/shiny-prerendered" data-context="server">
session$onSessionEnded(function() {
        learnr:::session_stop_event(session)
      })
</script>
 
<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-mean1-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-mean1-code-editor`)), session)
output$`tutorial-exercise-mean1-output` <- renderUI({
  `tutorial-exercise-mean1-result`()
})
</script>
 
<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-mean2-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-mean2-code-editor`)), session)
output$`tutorial-exercise-mean2-output` <- renderUI({
  `tutorial-exercise-mean2-result`()
})
</script>
 
<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-sampling1-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-sampling1-code-editor`)), session)
output$`tutorial-exercise-sampling1-output` <- renderUI({
  `tutorial-exercise-sampling1-result`()
})
</script>
 
<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-sampling2-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-sampling2-code-editor`)), session)
output$`tutorial-exercise-sampling2-output` <- renderUI({
  `tutorial-exercise-sampling2-result`()
})
</script>
 
<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-sampling3-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-sampling3-code-editor`)), session)
output$`tutorial-exercise-sampling3-output` <- renderUI({
  `tutorial-exercise-sampling3-result`()
})
</script>
 
<script type="application/shiny-prerendered" data-context="server">
`tutorial-exercise-sampling4-result` <- learnr:::setup_exercise_handler(reactive(req(input$`tutorial-exercise-sampling4-code-editor`)), session)
output$`tutorial-exercise-sampling4-output` <- renderUI({
  `tutorial-exercise-sampling4-result`()
})
</script>
 
<script type="application/shiny-prerendered" data-context="server">
learnr:::question_prerendered_chunk(structure(list(type = "learnr_radio", label = "quiz-1", question = structure("Consider a situation where we have sampled repeatedly from a population, calculated a mean for each sample and drawn a frequency histogram of the means. Which of the following is correct?", html = TRUE, class = c("html", "character")), answers = list(structure(list(id = "lnr_ans_80e10bd",     option = "The distribution of means will always be normal",     value = "The distribution of means will always be normal",     label = structure("The distribution of means will always be normal", html = TRUE, class = c("html",     "character")), correct = FALSE, message = NULL), class = c("tutorial_question_answer", "tutorial_quiz_answer")), structure(list(id = "lnr_ans_43addea",     option = "The distribution of means will always be centred on the population mean",     value = "The distribution of means will always be centred on the population mean",     label = structure("The distribution of means will always be centred on the population mean", html = TRUE, class = c("html",     "character")), correct = FALSE, message = NULL), class = c("tutorial_question_answer", "tutorial_quiz_answer")), structure(list(id = "lnr_ans_aed2a37",     option = "The distribution of means will show positive skew if the underlying population is itself positively skewed",     value = "The distribution of means will show positive skew if the underlying population is itself positively skewed",     label = structure("The distribution of means will show positive skew if the underlying population is itself positively skewed", html = TRUE, class = c("html",     "character")), correct = FALSE, message = NULL), class = c("tutorial_question_answer", "tutorial_quiz_answer")), structure(list(id = "lnr_ans_8fce8a3",     option = "As the number of samples increases, the distribution of means will become closer to a normal distribution",     value = "As the number of samples increases, the distribution of means will become closer to a normal distribution",     label = structure("As the number of samples increases, the distribution of means will become closer to a normal distribution", html = TRUE, class = c("html",     "character")), correct = TRUE, message = NULL), class = c("tutorial_question_answer", "tutorial_quiz_answer")), structure(list(id = "lnr_ans_4dbe115",     option = "If the number of samples is greater than 30, the mean of the sampling distribution will be equal to the population mean",     value = "If the number of samples is greater than 30, the mean of the sampling distribution will be equal to the population mean",     label = structure("If the number of samples is greater than 30, the mean of the sampling distribution will be equal to the population mean", html = TRUE, class = c("html",     "character")), correct = FALSE, message = NULL), class = c("tutorial_question_answer", "tutorial_quiz_answer"))), button_labels = list(submit = structure("Submit Answer", html = TRUE, class = c("html", "character")), try_again = structure("Try Again", html = TRUE, class = c("html", "character"))), messages = list(correct = structure("Correct!", html = TRUE, class = c("html", "character")), try_again = structure("Incorrect", html = TRUE, class = c("html", "character")), incorrect = structure("Incorrect", html = TRUE, class = c("html", "character")), message = NULL, post_message = NULL), ids = list(    answer = "quiz-1-answer", question = "quiz-1"), loading = structure("<strong>Loading:<\u002fstrong> \nConsider a situation where we have sampled repeatedly from a population, calculated a mean for each sample and drawn a frequency histogram of the means. Which of the following is correct?\n<br/><br/><br/>", html = TRUE, class = c("html", "character")), random_answer_order = FALSE, allow_retry = FALSE,     seed = 1836525266.6448, options = list()), class = c("learnr_radio", "tutorial_question")))
</script>
 
<script type="application/shiny-prerendered" data-context="server">
learnr:::question_prerendered_chunk(structure(list(type = "learnr_radio", label = "quiz-2", question = structure("Which of these cases would have the narrowest sampling distribution of means?", html = TRUE, class = c("html", "character")), answers = list(structure(list(id = "lnr_ans_6d266ea",     option = "500 samples each of 100 from a population with standard deviation  = 2",     value = "500 samples each of 100 from a population with standard deviation  = 2",     label = structure("500 samples each of 100 from a population with standard deviation  = 2", html = TRUE, class = c("html",     "character")), correct = TRUE, message = NULL), class = c("tutorial_question_answer", "tutorial_quiz_answer")), structure(list(id = "lnr_ans_df7159c",     option = "500 samples each of 50 from a population with standard deviation  = 2",     value = "500 samples each of 50 from a population with standard deviation  = 2",     label = structure("500 samples each of 50 from a population with standard deviation  = 2", html = TRUE, class = c("html",     "character")), correct = FALSE, message = NULL), class = c("tutorial_question_answer", "tutorial_quiz_answer")), structure(list(id = "lnr_ans_7b4dd76",     option = "1000 samples each of 50 from a population with standard deviation  = 3",     value = "1000 samples each of 50 from a population with standard deviation  = 3",     label = structure("1000 samples each of 50 from a population with standard deviation  = 3", html = TRUE, class = c("html",     "character")), correct = FALSE, message = NULL), class = c("tutorial_question_answer", "tutorial_quiz_answer")), structure(list(id = "lnr_ans_2e101f9",     option = "500 samples each of 100 from a population with standard deviation  = 3",     value = "500 samples each of 100 from a population with standard deviation  = 3",     label = structure("500 samples each of 100 from a population with standard deviation  = 3", html = TRUE, class = c("html",     "character")), correct = FALSE, message = NULL), class = c("tutorial_question_answer", "tutorial_quiz_answer")), structure(list(id = "lnr_ans_ba6d8b0",     option = "10000 samples each of 50 from a population with standard deviation  = 4",     value = "10000 samples each of 50 from a population with standard deviation  = 4",     label = structure("10000 samples each of 50 from a population with standard deviation  = 4", html = TRUE, class = c("html",     "character")), correct = FALSE, message = NULL), class = c("tutorial_question_answer", "tutorial_quiz_answer"))), button_labels = list(submit = structure("Submit Answer", html = TRUE, class = c("html", "character")), try_again = structure("Try Again", html = TRUE, class = c("html", "character"))), messages = list(correct = structure("Correct!", html = TRUE, class = c("html", "character")), try_again = structure("Incorrect", html = TRUE, class = c("html", "character")), incorrect = structure("Incorrect", html = TRUE, class = c("html", "character")), message = NULL, post_message = NULL), ids = list(    answer = "quiz-2-answer", question = "quiz-2"), loading = structure("<strong>Loading:<\u002fstrong> \nWhich of these cases would have the narrowest sampling distribution of means?\n<br/><br/><br/>", html = TRUE, class = c("html", "character")), random_answer_order = FALSE, allow_retry = FALSE,     seed = 1622938938.24426, options = list()), class = c("learnr_radio", "tutorial_question")))
</script>
 <!--html_preserve-->
<script type="application/shiny-prerendered" data-context="dependencies">
{"type":"list","attributes":{},"value":[{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["jquery"]},{"type":"character","attributes":{},"value":["1.11.3"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/jquery"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["jquery.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.4"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["bootstrap"]},{"type":"character","attributes":{},"value":["3.3.5"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/bootstrap"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["viewport"]}},"value":[{"type":"character","attributes":{},"value":["width=device-width, initial-scale=1"]}]},{"type":"character","attributes":{},"value":["js/bootstrap.min.js","shim/html5shiv.min.js","shim/respond.min.js"]},{"type":"character","attributes":{},"value":["css/bootstrap.min.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.4"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["pagedtable"]},{"type":"character","attributes":{},"value":["1.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/pagedtable-1.1"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["js/pagedtable.js"]},{"type":"character","attributes":{},"value":["css/pagedtable.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.4"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["highlightjs"]},{"type":"character","attributes":{},"value":["9.12.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/highlightjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["highlight.js"]},{"type":"character","attributes":{},"value":["textmate.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.4"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial"]},{"type":"character","attributes":{},"value":["0.10.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial.js"]},{"type":"character","attributes":{},"value":["tutorial.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial-autocompletion"]},{"type":"character","attributes":{},"value":["0.10.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial-autocompletion.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial-diagnostics"]},{"type":"character","attributes":{},"value":["0.10.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial-diagnostics.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial-format"]},{"type":"character","attributes":{},"value":["0.10.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmarkdown/templates/tutorial/resources"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial-format.js"]},{"type":"character","attributes":{},"value":["tutorial-format.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["jquery"]},{"type":"character","attributes":{},"value":["1.11.3"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/jquery"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["jquery.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.4"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["navigation"]},{"type":"character","attributes":{},"value":["1.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/navigation-1.1"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tabsets.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.4"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["highlightjs"]},{"type":"character","attributes":{},"value":["9.12.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/highlightjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["highlight.js"]},{"type":"character","attributes":{},"value":["default.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.4"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["jquery"]},{"type":"character","attributes":{},"value":["1.11.3"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/jquery"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["jquery.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.4"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["font-awesome"]},{"type":"character","attributes":{},"value":["5.1.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["rmd/h/fontawesome"]}]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["css/all.css","css/v4-shims.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["rmarkdown"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["2.4"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["bootbox"]},{"type":"character","attributes":{},"value":["4.4.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/bootbox"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["bootbox.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["idb-keyvalue"]},{"type":"character","attributes":{},"value":["3.2.0"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/idb-keyval"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["idb-keyval-iife-compat.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[false]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial"]},{"type":"character","attributes":{},"value":["0.10.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial.js"]},{"type":"character","attributes":{},"value":["tutorial.css"]},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial-autocompletion"]},{"type":"character","attributes":{},"value":["0.10.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial-autocompletion.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["tutorial-diagnostics"]},{"type":"character","attributes":{},"value":["0.10.1"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/tutorial"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["tutorial-diagnostics.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["ace"]},{"type":"character","attributes":{},"value":["1.2.6"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/ace"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["ace.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["name","version","src","meta","script","stylesheet","head","attachment","package","all_files","pkgVersion"]},"class":{"type":"character","attributes":{},"value":["html_dependency"]}},"value":[{"type":"character","attributes":{},"value":["clipboardjs"]},{"type":"character","attributes":{},"value":["1.5.15"]},{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["file"]}},"value":[{"type":"character","attributes":{},"value":["lib/clipboardjs"]}]},{"type":"NULL"},{"type":"character","attributes":{},"value":["clipboard.min.js"]},{"type":"NULL"},{"type":"NULL"},{"type":"NULL"},{"type":"character","attributes":{},"value":["learnr"]},{"type":"logical","attributes":{},"value":[true]},{"type":"character","attributes":{},"value":["0.10.1"]}]}]}
</script>
<!--/html_preserve-->
<!--html_preserve-->
<script type="application/shiny-prerendered" data-context="execution_dependencies">
{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["packages"]}},"value":[{"type":"list","attributes":{"names":{"type":"character","attributes":{},"value":["packages","version"]},"class":{"type":"character","attributes":{},"value":["data.frame"]},"row.names":{"type":"integer","attributes":{},"value":[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38]}},"value":[{"type":"character","attributes":{},"value":["backports","base","checkmate","compiler","datasets","digest","ellipsis","evaluate","fastmap","graphics","grDevices","htmltools","htmlwidgets","httpuv","jsonlite","knitr","later","learnr","magrittr","markdown","methods","mime","promises","R6","Rcpp","rlang","rmarkdown","rprojroot","shiny","stats","stringi","stringr","tools","utils","withr","xfun","xtable","yaml"]},{"type":"character","attributes":{},"value":["1.1.10","4.0.2","2.0.0","4.0.2","4.0.2","0.6.25","0.3.1","0.14","1.0.1","4.0.2","4.0.2","0.5.0","1.5.1","1.5.4","1.7.1","1.30","1.1.0.1","0.10.1","1.5","1.1","4.0.2","0.9","1.1.1","2.4.1","1.0.5","0.4.7","2.4","1.3-2","1.5.0","4.0.2","1.5.3","1.4.0","4.0.2","4.0.2","2.3.0","0.18","1.8-4","2.2.1"]}]}]}
</script>
<!--/html_preserve-->
</div>

</div> <!-- topics -->

<div class="topicsContainer">
<div class="topicsPositioner">
<div class="band">
<div class="bandContent topicsListContainer">

<!-- begin doc-metadata -->
<div id="doc-metadata">
<h2 class="title toc-ignore" style="display:none;">Sampling and uncertainty 1: Sampling distributions</h2>
<h4 class="author"><em>Rob Knell</em></h4>
</div>
<!-- end doc-metadata -->

</div> <!-- bandContent.topicsListContainer -->
</div> <!-- band -->
</div> <!-- topicsPositioner -->
</div> <!-- topicsContainer -->


</div> <!-- bandContent page -->
</div> <!-- pageContent band -->




<script>
// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});
</script>


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>


</body>

</html>
